Modified to handle substitution of @BINDIR@, and some non-templated files.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,9 @@
 #!/bin/sh
 
-expr=""
+if [ -z "$BINDIR" ]; then
+  echo "$0: BINDIR must be set"
+  exit 1
+fi
 
 case `echo 'a\c'` in
   'a\c')
@@ -17,7 +20,9 @@ case `echo 'a\c'` in
     ;;
 esac
 
-process() {
+perl="$perl; s|\@BINDIR\@|$BINDIR|g"
+
+process_template() {
   {
     sed -e "s/%PROGRAM%/$2/g" template.sh
     tail +2 $1 | perl -p -e "$perl"
@@ -25,13 +30,26 @@ process() {
   chmod +x $2
 }
 
-for file in "$@"; do
-  out=`basename $file .in`
-  file=$out.in
-  if ! [ -e $file ]; then
-    echo "configure: Skipping missing file '$file'"
-  else
-    echo "Processing $file -> $out"
-    process $file $out
-  fi
-done
+process_notemplate() {
+  perl -p -e "$perl" <$1 >$2
+  chmod +x $2
+}
+
+process_list() {
+  processor=$1
+  shift
+  for file in "$@"
+  do
+    if ! [ -e $file ]
+    then
+      echo "$0: Skipping missing file '$file'"
+    else
+      out=`basename $file .in`
+      echo "Processing $file => $out"
+      $processor $file $out
+    fi
+  done
+}
+
+process_list process_template svc-*.in
+process_list process_notemplate svscan-*.in
