Modified configure to use a template file for the standardized parts.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19,23 +19,7 @@ esac
 
 process() {
   {
-    echo '#!/bin/sh'
-    echo 'set -e'
-    echo 'PATH="$PATH:/usr/local/bin"'
-    echo 'export PATH'
-    echo 'cd "${SVSCANDIR-/service}"'
-    echo 'fatal() {'
-    echo '  echo "'$2': Fatal error: $@" >&2'
-    echo '  exit 1'
-    echo '}'
-    echo 'usage() {'
-    echo '  args=$1; min=$2; max=$3; shift 3'
-    echo '  if [ $args -lt $min -o $args -gt $max ]; then'
-    echo '    echo "$0: usage: '$2' $@" >&2'
-    echo '    exit 1'
-    echo '  fi'
-    echo '}'
-    echo
+    sed -e "s/%PROGRAM%/$2/g" template.sh
     tail +2 $1 | perl -p -e "$perl"
   } >$2
   chmod +x $2
@@ -43,6 +27,11 @@ process() {
 
 for file in "$@"; do
   out=`basename $file .in`
-  echo "Processing $file -> $out"
-  process $file $out
+  file=$out.in
+  if ! [ -e $file ]; then
+    echo "configure: Skipping missing file '$file'"
+  else
+    echo "Processing $file -> $out"
+    process $file $out
+  fi
 done
