Finalized paths and defaults.

diff --git a/svc-multilog.in b/svc-multilog.in
--- a/svc-multilog.in
+++ b/svc-multilog.in
@@ -1,19 +1,28 @@
 #!/bin/sh
 usage $# 1 1 "log-directory"
+set -x
+
+if [ ! -d log -o ! -d log/supervise ]
+then
+  echo "Error: $0 must be run from svscan."
+  exit 1
+fi
 
 log="$1"
 
-confdir=/etc/svclog.d
+logdir="${SVCLOGDIR-/var/log}/$log"
+confdir="./log/control"
+dfltdir="${SVCLOGCONF-/etc/multilog}"
 
 read() {
   local param=$1
   shift
-  if [ -s $confdir/"$log"/$param ]
+  if [ -s $confdir/$param ]
   then
-    head -1 $confdir/"$log"/$param
-  elif [ -s $confdir/DEFAULT/$param ]
+    head -1 $confdir/$param
+  elif [ -s $dfltdir/$param ]
   then
-    head -1 $confdir/DEFAULT/$param
+    head -1 $dfltdir/param
   else
     echo "$@"
   fi
@@ -21,10 +30,20 @@ read() {
 
 size=`read size 99999`
 number=`read number 10`
-processor=`read processor ""`
-if [ -n "$processor" ]
+owner=`read owner ""`
+
+if [ -n "$owner" ]; then setuidgid="setuidgid $owner" fi
+
+# The processor is a special case:
+processor=""
+if [ -x "$confdir/processor" ]
 then
-  processor="!$processor"
+  processor="'!$confdir/processor'"
 fi
 
-echo exec multilog t n$number s$size /var/log/"$log"
+if [ -x "$dfltdir/processor" ]
+then
+  processor="'!$dfltdir/processor' $processor"
+fi
+
+echo "exec $setuidgid multilog t n'$number' s'$size' $processor '$logdir'"
